#FAKE NEWS DETECTION


## Word Frequency Distribution

### Word Frequency Distribution

**Meaning:** Word frequency distribution refers to the count of how often each word appears in a given text or corpus. It's a fundamental statistical measure in natural language processing (NLP).

**Use Cases:**
*   **Text Analysis:** Understanding the most common words can reveal the main topics or themes of a document.
*   **Information Retrieval:** Important for indexing documents and query processing.
*   **Feature Engineering:** Word frequencies can be used as features for machine learning models (e.g., sentiment analysis, text classification).
*   **Stop Word Removal:** Identifying and removing very common words (like 'the', 'is', 'a') that often carry little meaning.

In [ ]:
from collections import Counter
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

def word_frequency(text):
    words = word_tokenize(text.lower())
    return Counter(words)

text = "NLP is amazing. NLP makes machines understand text."
print("Word Frequencies:", word_frequency(text))

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


Word Frequencies: Counter({'nlp': 2, '.': 2, 'is': 1, 'amazing': 1, 'makes': 1, 'machines': 1, 'understand': 1, 'text': 1})


## BOW

### Bag of Words (BoW)

**Meaning:** The Bag of Words (BoW) model is a simplifying representation used in NLP and information retrieval. In this model, a text (such as a sentence or a document) is represented as a "bag" (multiset) of its words, disregarding grammar and even word order but keeping multiplicity.

**Use Cases:**
*   **Text Classification:** A common technique to convert text into numerical feature vectors that can be fed into machine learning algorithms for tasks like spam detection, sentiment analysis, or topic classification.
*   **Document Similarity:** Comparing the BoW representations of two documents can give a measure of how similar their content is.
*   **Information Retrieval:** Used in search engines to determine the relevance of documents to a user's query.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "NLP is fun and exciting",
    "Machines understand NLP and text",
    "Text processing is part of NLP"
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

print("Feature Names:", vectorizer.get_feature_names_out())
print("BoW Representation:")
print(X.toarray())

Feature Names: ['and' 'exciting' 'fun' 'is' 'machines' 'nlp' 'of' 'part' 'processing'
 'text' 'understand']
BoW Representation:
[[1 1 1 1 0 1 0 0 0 0 0]
 [1 0 0 0 1 1 0 0 0 1 1]
 [0 0 0 1 0 1 1 1 1 1 0]]


This code demonstrates the Bag of Words (BoW) model using `CountVectorizer` from `sklearn.feature_extraction.text`.

*   It takes a `corpus` (a collection of documents/sentences).
*   `CountVectorizer` converts the text documents into a matrix of token counts. Each row represents a document, and each column represents a unique word from the corpus. The value in a cell is the frequency of that word in that document.
*   `get_feature_names_out()` shows the unique words (vocabulary) that form the columns of the matrix.

## TF-IDF

### TF-IDF (Term Frequency-Inverse Document Frequency)

**Meaning:** TF-IDF is a numerical statistic that reflects how important a word is to a document in a collection or corpus. It is often used as a weighting factor in information retrieval and text mining. The TF-IDF value increases proportionally to the number of times a word appears in the document but is offset by the frequency of the word in the corpus, which helps to adjust for the fact that some words appear more frequently in general.

**Components:**
*   **Term Frequency (TF):** Measures how frequently a term appears in a document. Higher frequency means higher importance within that document.
*   **Inverse Document Frequency (IDF):** Measures how important a term is across the whole corpus. Rare words across the corpus have a higher IDF, indicating more unique and potentially important information.

**Use Cases:**
*   **Search Engine Ranking:** Essential for ranking documents by relevance in search queries.
*   **Text Summarization:** Identifying keywords that are highly relevant to a document but not overly common.
*   **Topic Modeling:** Helps in discovering underlying themes or topics in a collection of texts.
*   **Recommendation Systems:** Finding documents or articles similar to a user's interests based on content.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)

print("Feature Names:", vectorizer.get_feature_names_out())
print("TF-IDF Representation:")
print(X.toarray())

Feature Names: ['and' 'exciting' 'fun' 'is' 'machines' 'nlp' 'of' 'part' 'processing'
 'text' 'understand']
TF-IDF Representation:
[[0.40619178 0.53409337 0.53409337 0.40619178 0.         0.31544415
  0.         0.         0.         0.         0.        ]
 [0.40619178 0.         0.         0.         0.53409337 0.31544415
  0.         0.         0.         0.40619178 0.53409337]
 [0.         0.         0.         0.35829137 0.         0.27824521
  0.4711101  0.4711101  0.4711101  0.35829137 0.        ]]


This code calculates the TF-IDF representation for the same `corpus` using `TfidfVectorizer` from `sklearn.feature_extraction.text`.

*   Instead of just counts, `TfidfVectorizer` computes a weighted score for each word in each document.
*   Words that are frequent in a document but rare across the entire corpus will have higher TF-IDF scores, indicating their significance.

## NLP Task - Keyword Extraction

### NLP Task - Keyword Extraction

**Meaning:** Keyword extraction is the process of automatically identifying the most important or relevant words and phrases in a text. These keywords typically represent the main topics or themes of the document.

**Use Cases:**
*   **Content Indexing:** Automatically tagging articles or documents with relevant keywords for easier search and categorization.
*   **Text Summarization:** Identifying key terms can help in creating concise summaries of longer texts.
*   **Information Retrieval:** Improving the accuracy of search results by matching queries with document keywords.
*   **Recommendation Systems:** Suggesting related content based on the keywords of what a user has previously consumed.
*   **Sentiment Analysis:** Keywords can highlight aspects of a product or service that are discussed positively or negatively.

In [ ]:
import numpy as np

feature_array = np.array(vectorizer.get_feature_names_out())
importance = np.argsort(X.toarray()).flatten()[::-1]

keywords = feature_array[importance[:5]]
print("Top Keywords:", keywords)

Top Keywords: ['processing' 'of' 'part' 'is' 'text']


This code snippet performs a basic form of keyword extraction using the TF-IDF scores calculated previously.

*   It sorts the TF-IDF scores for each word (across all documents) and identifies the words with the highest scores.
*   The assumption is that words with higher TF-IDF values are more indicative of the document's content and thus serve as good keywords.
*   `np.argsort()` helps in getting the indices that would sort an array, and `[::-1]` reverses it to get the indices of the highest values first.